laxity/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/<int:patient_pk>', views.create_laxity, name='create_laxity'),
    path('list/<int:patient_pk>', views.list_laxity, name='list_laxity'),
    path('delete/<int:laxity_pk>/<int:patient_pk>/', views.delete_laxity, name='delete_laxity'),
    path('detail/<int:laxity_pk>', views.laxity_detail, name='laxity_detail'),
]

medical_records/urls.py
from django.contrib import admin
from django.urls import path, include
from patient_profile import views as patient_profile_views
from django.conf.urls.static import static
from django.conf import settings
from payments import views as payments_views


urlpatterns = [
    path('master/', admin.site.urls),

    # Auth
    path('login/', patient_profile_views.login_user, name='loginuser'),
    path('logout/', patient_profile_views.logout_user, name='logoutuser'),

    # Patient Profile
    path('', patient_profile_views.create_patient_profile, name='patient_profile'),

    # Administrator
    path('admin/', patient_profile_views.admin, name='admin'),
    path('patient/<int:patient_pk>', patient_profile_views.patient_detail, name='patient_detail'),
    path('patient/update/<int:patient_pk>', patient_profile_views.patient_update, name='patient_update'),
    path('patient/<int:patient_pk>/delete', patient_profile_views.patient_delete, name='patient_delete'),

    #Payments
    path('payment/create/<int:patient_pk>', payments_views.create_payment, name='create_payment'),
    path('payments/<int:patient_pk>', payments_views.list_payment, name='list_payment'),
    path('payment/delete/<int:payment_pk>/<int:patient_pk>/', payments_views.delete_payment, name='delete_payment'),
    path('payment/list/', payments_views.all_payments, name='all_payments'),

    # Orthodontics urls
    path('orthdontics/', include('orthodontic.urls')),

    # Laxity urls
    path('laxity/', include('laxity.urls')),

    # Pain Mapping urls
    path('pain_mapping/', include('pain_mapping.urls')),

    # Muscle Palpation urls
    path('muscle_palpation/', include('muscle_palpation.urls')),

    # Annotation urls
    path('annotations/', include('annotations.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

muscle_palpation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/<int:patient_pk>', views.create_muscle_palpation, name='create_muscle_palpation'),
    path('list/<int:patient_pk>', views.list_muscle_palpation, name='list_muscle_palpation'),
    path('delete/<int:palpation_pk>/<int:patient_pk>/', views.delete_muscle_palpation, name='delete_muscle_palpation'),
    path('detail/<int:palpation_pk>', views.muscle_palpation_detail, name='muscle_palpation_detail'),
]

annotations/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from patient_profile.models import PatientProfile


class Annotation(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    date = models.DateField(auto_now_add=True)
    patient = models.ForeignKey(PatientProfile, on_delete=CASCADE)

    def __str__(self):
        return self.title

muscle_palpation/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from patient_profile.models import PatientProfile


class MusclePalpation(models.Model):
    masseter_right = models.BooleanField(default=False)
    masseter_left = models.BooleanField(default=False)
    temporalis_right = models.BooleanField(default=False)
    temporalis_left = models.BooleanField(default=False)
    ecm_right = models.BooleanField(default=False)
    ecm_left = models.BooleanField(default=False)
    digastric_right = models.BooleanField(default=False)
    digastric_left = models.BooleanField(default=False)
    occipital_right = models.BooleanField(default=False)
    occipital_left = models.BooleanField(default=False)
    pc_right = models.BooleanField(default=False)
    pc_left = models.BooleanField(default=False)
    trapezius_right = models.BooleanField(default=False)
    trapezius_left = models.BooleanField(default=False)
    note = models.TextField(max_length=500, blank=True )

    created_at = models.DateField(auto_now_add=True)
    patient = models.ForeignKey(PatientProfile, on_delete=CASCADE)

    def __str__(self):
        return self.created_at

# Masetero
# Temporal
# ECM
# Digastrico
# Occipital
# PC
# Trapecio

muscle_palpation/forms.py
from django.forms import ModelForm, fields
from .models import MusclePalpation


class MusclePalpationForm(ModelForm):
    class Meta:
        model = MusclePalpation
        fields = [
            'masseter_right',
            'masseter_left',
            'temporalis_right',
            'temporalis_left',
            'ecm_right',
            'ecm_left',
            'digastric_right',
            'digastric_left',
            'occipital_right',
            'occipital_left',
            'pc_right',
            'pc_left',
            'trapezius_right',
            'trapezius_left',
            'note',
            'patient'
        ]

muscle_palpation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import MusclePalpationForm
from .models import MusclePalpation
from patient_profile.models import PatientProfile
from django.contrib.auth.decorators import login_required


def create_muscle_palpation(request, patient_pk):
    patient = PatientProfile.objects.get(pk=patient_pk)
    patient_muscle_palpations = MusclePalpation.objects.filter(patient__pk=patient_pk)

    context = {
        'patient_muscle_palpations': patient_muscle_palpations, 
        'patient': patient, 
        'succes_msg': "examen ortodontico registrado exitosamente!",
        'form': MusclePalpationForm,
    }

    if request.method == 'GET':
        return render(request, 'muscle_palpation/muscle_palpation_form.html', context)
    else:
        try:
            form = MusclePalpationForm(request.POST)
            form.save()
            return render(request, 'muscle_palpation/muscle_palpation_list.html', context)
        except ValueError:
            context['error'] = 'formato equivocado'
            return render(request, 'muscle_palpation/muscle_palpation_form.html', context)


def list_muscle_palpation(request, patient_pk):
    patient = PatientProfile.objects.get(pk=patient_pk)
    patient_muscle_palpations = MusclePalpation.objects.filter(patient__pk=patient_pk)
    context = {
        'patient_muscle_palpations': patient_muscle_palpations, 
        'patient': patient
    }

    return render(request, 'muscle_palpation/muscle_palpation_list.html', context)


@login_required(login_url='loginuser')
def delete_muscle_palpation(request, palpation_pk, patient_pk):
    muscle_palpation = get_object_or_404(MusclePalpation, pk=palpation_pk)
    if request.method == 'POST':
        muscle_palpation.delete()
        patient = PatientProfile.objects.get(pk=patient_pk)
        patient_muscle_palpations = MusclePalpation.objects.filter(patient__pk=patient_pk)
        context = {
        'patient_muscle_palpations': patient_muscle_palpations, 
        'patient': patient,
        'deleted_msg': 'Examen eliminado'
        }
        return render(request, 'muscle_palpation/muscle_palpation_list.html', context)


@login_required(login_url='loginuser')
def muscle_palpation_detail(request, palpation_pk):
    muscle_palpation = get_object_or_404(MusclePalpation, pk=palpation_pk)
    return render(request, 'muscle_palpation/muscle_palpation_detail.html', {'muscle_palpation': muscle_palpation})

templates/muscle_palpation/muscle_palpation_detail.html
{% extends "base.html" %}
    {% block content %}
    {% load i18n %}
    {% load static %}
    <div class="row">
        <div class="col text-center">
            <h2>Palpacion muscular</h2>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h4>Test hecho el:  {% language 'es' %}{{ muscle_palpation.created_at }}{% endlanguage %}</h4>
        </div>
    </div>
        <div class="row">
            <div class="col">
                <img class="img-fluid" src="{% static 'images/right_side.png' %}" alt="Palpacion">
            </div>
            <div class="col align-self-center">
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.masseter_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Masetero</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.masseter_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.temporalis_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Temporal</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.temporalis_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.ecm_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>ECM</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.ecm_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.digastric_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Digastrico</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.digastric_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.occipital_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Occipital</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.occipital_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.pc_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>PC</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.pc_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.trapezius_right %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Trapecio</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            {% if muscle_palpation.trapezius_left %}
                                <i class="bi bi-check-square-fill text-success " style="font-size: 1.5rem;"></i>
                            {% else %}
                                <i class="bi bi-x-square-fill text-danger" style="font-size: 1.5rem;"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <img class="img-fluid" src="{% static 'images/left_side.png' %}" alt="Palpacion">
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-6">
                <div class="form-floating">
                    <textarea class="form-control" id="id_body"  name="note" style="height: 15rem" readonly>{{ muscle_palpation.note }}</textarea>
                    <label for="id_body">Nota:</label>
                </div>
            </div>
        </div>
    {% endblock %}

templates/muscle_palpation/muscle_palpation_form.html
{% extends "base.html" %}
    {% block content %}

    {% load static %}

    <div class="row">
        <div class="col">
            {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col text-center"><h2>Palpacion muscular</h2></div>
    </div>
    
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <img class="img-fluid" src="{% static 'images/right_side.png' %}" alt="Palpacion">
            </div>
            <div class="col align-self-center">
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="masseter_right" name="masseter_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Masetero</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="masseter_left" name="masseter_left">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="temporalis_right" name="temporalis_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Temporal</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="temporalis_left" name="temporalis_left">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="ecm_right" name="ecm_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>ECM</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="ecm_left" name="ecm_left">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="digastric_right" name="digastric_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Digastrico</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="digastric_left" name="digastric_left">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="occipital_right" name="occipital_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Occipital</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="occipital_left" name="occipital_left">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="pc_right" name="pc_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>PC</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="pc_left" name="pc_left">
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="trapezius_right" name="trapezius_right">
                        </div>
                    </div>
                    <div class="col-6 text-center">
                        <span>Trapecio</span>
                    </div>
                    <div class="col-3 d-flex justify-content-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="trapezius_left" name="trapezius_left">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <img class="img-fluid" src="{% static 'images/left_side.png' %}" alt="Palpacion">
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-6">
                <div class="form-floating">
                    <textarea class="form-control" id="id_body" placeholder="nota"  name="note" style="height: 15rem"></textarea>
                    <label for="id_body">Nota:</label>
                </div>
            </div>
        </div>
        <input id="id_patient" name="patient" type="hidden" value="{{ patient.id }}">
        <div class="row mb-3">
            <div class="col">
                <button class="btn btn-purple" type="submit">Registrar</button>
            </div>
        </div>
    </form>
    {% endblock %}

templates/muscle_palpation/muscle_palpation_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col">
            {% if succes_msg %}
            <div class="alert alert-success" role="alert">
                {{ succes_msg }}
            </div>
            {% elif deleted_msg %}
            <div class="alert alert-success" role="alert">
                {{ deleted_msg }}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1>Historial de: {{ patient.name }}</h1>
        </div>
        <div class="col align-self-center text-end">
            <a class="btn btn-outline-purple" href="{% url 'create_muscle_palpation' patient.id %}" role="button">Nueva palpitacion muscular</a>
        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col">
            <h4>Examenes de palpacion:</h4>
            <table class="table table-striped">
                <thead style="background-color: #322232; color: #FFFFFF;">
                    <tr>
                        <th scope="col">Fecha de creacion del examen</th>
                        <th cope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for palpation in patient_muscle_palpations %}
                    <tr>
                        <th><a href="{% url 'muscle_palpation_detail' palpation.id %}">{% language 'es' %}{{ palpation.created_at }}{% endlanguage %}</a></th>
                        <th>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                data-bs-target="#delete-server-{{palpation.id}}">
                                Borrar
                            </button>
                        </th>
                    </tr>
                    <!-- Modal -->
                    <div class="modal fade" id="delete-server-{{palpation.id}}" tabindex="-1"
                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Borrar?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>Atencion!</p>
                                    <p>esta apunto de borrar el examen ortodontico</p>
                                    <p>perfil facial: {{palpation.created_at }}</p>
                                </div>
                                <div class="modal-footer">
                                    <form action="{% url 'delete_muscle_palpation' palpation.id patient.id %}"
                                        method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">Eliminar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}